### PR TITLE
fix: selected version flickering after each page load

### LINKED ISSUE #88: UI: Release ordering + listing
- Releases should be ordered based on the recent release first
- Releases should have stable / beta tags

image

reference image:
image

### PR DESCRIPTION
**Pull request by aniketkatkar97**
Fixes issue in comment https://github.com/open-metadata/docs-v1/issues/93#issuecomment-1531496673
Fixes #88 

- [x] Fixed an issue where the selected version was flickering after each page load
- [x] Order of version selection options changed to show the latest version first in the list

https://user-images.githubusercontent.com/51777795/235685130-2e507a50-855b-443e-8762-50df9a14214a.mov

### CODE REVIEW

File: components/TopNav/TopNav.tsx [hunk 1]
```diff
@@ -26,12 +26,13 @@ const searchClient = algoliasearch(
   process.env.NEXT_PUBLIC_ALGOLIA_API_KEY
 );
 
-export default function TopNav() {
+interface TopNavProps {
+  versionsList: Array<SelectOption<string>>;
```
Comment (chirag-madlani) [inline components/TopNav/TopNav.tsx:30]: versions

**Review by chirag-madlani — APPROVED** [review]
