### PR TITLE
ui: Improvements and bug fixes

### LINKED ISSUE #57: Side navigation panel improvements
- [ ] The side panel collapses in case the `Code Preview` component is present in the page content. the collapse behavior should be only for the smaller screens.
- [ ] Make the collapse and expand animation smoother.

### PR DESCRIPTION
**Pull request by aniketkatkar97**
fixes #57 

- [x] Changed layouts for pages for better UX

- [x] Made Side Nav panel collapse animation smoother

- [x] Logic to the auto collapse of SideNav panel on page with CodePreview improved

https://user-images.githubusercontent.com/51777795/233560829-e902f51f-98e9-4a96-aa36-0f7aa3a18c0c.mov

- [x] Fixed pin icon color

- [x] Fixed the error thrown from the CodeBlock component

### CODE REVIEW

File: components/CodePreview/CodeBlock/CodeBlock.tsx [hunk 1]
```diff
@@ -15,7 +22,7 @@ export default function CodeBlock({ children, fileName }: Props) {
   const [prevSelectedCode, setPrevSelectedCode] = useState<number>(1);
   const [copyText, setCopyText] = useState<string>("Copy");
   const preTag = useRef<HTMLPreElement>();
-  const codeBlockId = useMemo(() => uniqueId("code-block-container-"), []);
+  const [codeBlockId, setCodeBlockId] = useState<string>();
```
Comment (chirag-madlani) [inline components/CodePreview/CodeBlock/CodeBlock.tsx:25]: What was the issue with useMemo here?

File: pages/_error.tsx [hunk 2]
```diff
@@ -44,49 +45,49 @@ function Error() {
...
-                    key={`${tileInfo.link}${tileInfo.title}`}
-                    link={tileInfo.link}
-                    isExternalLink={tileInfo.isExternalLink}
-                    title={tileInfo.title}
-                  />
-                ))}
-              </TilesContainer>
-            </>
-          )}
+        <div>
```
Comment (chirag-madlani) [inline pages/_error.tsx:60]: Can use `<></>` here?

Comment (aniketkatkar97) [reply pages/_error.tsx:60]: Actually, we need that div to separate the content and footer from the SideNav component in the actual DOM.
